---
title: "Summary analysis NeVRo"
author: "eioe"
date: "17 1 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)

# disable scientific notation:
options(scipen=999)

# Set up paths: 
path_data <- here('Results')
```

## analysis accuracies:

```{r}
# Get summary data:
data_ls <- list()
conds <- c('mov', 'nomov')

for (cond in conds) {
  fname <- str_c('results_across_methods_', cond, '.csv')
  fpath <- file.path(path_data, fname)
  data_ls[[cond]] <- read_csv2(fpath)
}

data_df <- bind_rows(data_ls, .id = 'condition')

# select data of binary approaches only and put into long format:
data_bin <- data_df %>% 
  select(condition, Subject, LSTM, CSP) %>% 
  gather('LSTM', 'CSP', key = method, value = accuracy)



#Get single sample data:

model_pred_ls <- list()
model_targ_ls <- list()

data_pred_ls <- list()
data_targ_ls <- list()

data_pred_df <- NULL
data_targ_df <- NULL

samp_col_names <- sprintf('S%d', 1:270)

for (model in list('CSP', 'LSTM')) {

  for (cond in conds) {
    # Get prediction data:
    fname <- str_c('predictionTable', model, '_', cond, '.csv')
    fpath <- file.path(path_data, model, cond, fname)
    dat <- read_csv(fpath, col_names = FALSE)
    # Recode CSP data to [-1,1]:
    if (model == 'CSP') {
      dat <- dat %>% 
         mutate_at(vars(X2:X271), list(~recode(.,`0` = -1)))
    }
    data_pred_ls[[cond]] <- dat
    # Get target data:
    fname <- str_c('targetTable', model, '_', cond, '.csv')
    fpath <- file.path(path_data, model, cond, fname)
    dat <- read_csv(fpath, col_names = FALSE)
    # Recode CSP data to [-1,1]:
    if (model == 'CSP') {
      dat <- dat %>% 
         mutate_at(vars(X2:X271), list(~recode(.,`1` = -1, `2`= 1)))
    }
    data_targ_ls[[cond]] <- dat
  }
  
  data_pred_df <- bind_rows(data_pred_ls, .id = 'condition') %>% 
    rename_all(~c('Condition', 'Subject', samp_col_names))
  data_targ_df <- bind_rows(data_targ_ls, .id = 'condition') %>% 
    rename_all(~c('Condition', 'Subject', samp_col_names))
  
  model_pred_ls[[model]] <- data_pred_df
  model_targ_ls[[model]] <- data_targ_df
}
  


data_pred_df_full <- bind_rows(model_pred_ls, .id = 'Model') 
data_targ_df_full <- bind_rows(model_targ_ls, .id = 'Model') 

# combine, calc accuracy, and run binomial test:

binom_func <- function(n_corr_samps, n_samps_tot, p_guess) {
  binom.test(n_corr_samps, n_samps_tot, p = p_guess, alternative = "greater")
}

pred_success <- data_pred_df_full
pred_success[, samp_col_names] <- data_targ_df_full[, samp_col_names] == data_pred_df_full[, samp_col_names]

pred_success$Ncorrect <- rowSums(pred_success[, samp_col_names], na.rm = T)
pred_success$Ntot <- rowSums(!is.na(pred_success[, samp_col_names]))
pred_success$accuracy <- pred_success$Ncorrect/pred_success$Ntot
pred_success %>% 
  mutate(accuracy = Ncorrect/Ntot) %>% 
  rowwise() %>% 
  mutate(p_val = binom_func(Ncorrect, Ntot, 0.5)$p.value) %>% 
  select(-one_of(samp_col_names)) -> pred_success


# summary stats:
pred_success %>% 
  group_by(Model, Subject, Condition) %>% 
  summarise(Ncorr_avg = round(mean(Ncorrect)), 
            Ntot_avg = round(mean(Ntot))) %>% 
  mutate(accuracy = Ncorr_avg/Ntot_avg) %>% 
  rowwise() %>% 
  mutate(p_val = binom_func(Ncorr_avg, Ntot_avg, 0.5)$p.value) -> 
  accuracy_summary

accuracy_summary %>% 
  rownames_to_column() %>% 
  arrange(Model, Condition, accuracy) %>%
  mutate(mixed = as.integer(rowname)) %>% 
  select(-rowname) %>% 
  rownames_to_column()  %>% 
  arrange(mixed) -> ordered_subs
ordervar<- rep(as.integer(ordered_subs$rowname[1:45]), 2)

accuracy_summary %>%
  add_column(ordervar) %>% 
  mutate(Condition = recode(Condition, mov = 'Movement', nomov = 'No Movement'))  %>% 
  arrange(ordervar) %>% 
  ggplot(aes(x = ordervar, y = accuracy, col = Model)) + 
  facet_wrap(~Condition, scales = 'free') +
  geom_point(aes(shape = Model), size = 3) +
  theme_bw() + 
  scale_color_brewer(palette="Paired") +
  scale_shape_manual(values=c(13, 16, 17)) + 
  xlab('Subjects') + 
  theme(axis.text.x=element_blank()) -> pplot
pplot

# check correlation:
summary(lm(pred_success$accuracy[1:45]~pred_success$accuracy[46:90]))


######## old stuff (can probably be deprecated):


data_bin %>% 
  select(accuracy) %>% 
  na.omit() %>% 
  mutate(avg_n_corr_samples = round(accuracy * 180)) %>% 
  rowwise() %>% 
  mutate(p_val = binom_func(avg_n_corr_samples, 180, 0.5)$p.value) -> he
  



dat %>% 
  select(condition, Subject, LSTM, CSP) %>% 
  gather('LSTM', 'CSP', key = method, value = accuracy) %>% 
  group_by(method, condition) %>% 
  summarise(meanacc = mean(accuracy, na.rm=T)) ->
  outp



```


